#!/usr/bin/env bash

if (( $# != 1 )); then
    echo "Использование: $0 программа" >&2
    exit 1
fi

program=$1

if [[ ! -f $program ]]; then
    echo "Ошибка: файл '$program' не найден" >&2
    exit 1
fi

chmod 755 -- "$program"
sudo cp -- "$program" "/usr/local/bin/$(basename -- "$program")"

echo "Команда $(basename -- "$program") зарегистрирована"
